Enable env access for Deno builders (#10)
This enables all permissions for our Deno builder. Down the road, we likely expose a config option for which permissions you want to include.

I also updated out GHA setup to make sure I've committed the built files, since I keep forgetting to run `yarn watch`.

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -8,4 +8,10 @@ jobs:
       - name: Install Dependencies
         run: yarn
       - name: Run Tests
-        run: yarn build
+        run: |
+          yarn build
+
+          # Detects if you have changes to src/ that haven't been compiled into dist/
+          echo "⚠️ Checking for uncommitted dist/ changes. If this fails, try running 'yarn watch'."
+          git status
+          exit $(git status --porcelain=v1 2>/dev/null | wc -l)
